apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: Spring Boot service owned by ${{values.owner}}
  annotations:
    github.com/project-slug: ${{values.repoOwner}}/${{values.name}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{values.name}}
    developerhub.io/slo: "99.9% availability over 30 days"
  links:
    - url: https://github.com/${{values.repoOwner}}/${{values.name}}/blob/main/docs/runbook.md
      title: Runbook
spec:
  type: service
  lifecycle: experimental
  owner: group:default/${{values.owner}}
  system: developerhub
