{
 "title": "DeveloperHub Service",
 "templating": {
  "list": [
   { "name": "service", "query": "payment-service" },
   { "name": "namespace", "query": "payments-dev" }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$service\"}[5m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$service\",status=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum by(le)(rate(http_server_requests_seconds_bucket{application=\"$service\"}[5m])))"
    }
   ]
  }
 ]
}