package dev.developerhub;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import java.util.List;

/** Writes one Argo CD Application per service into the gitops repo (apps/<env>/<service>.yaml). */
@Component
public class GitOpsWriter {
  @Value("${developerhub.gitops-repo:hub-gitops}")
  private String gitopsRepo;

  private final GitHubClient github;

  public GitOpsWriter(GitHubClient github) { this.github = github; }

  /** @return url of the written Application manifest */
  public String write(String name, String owner, String env) {
    String login = github.login();
    if (!github.repoExists(login, gitopsRepo)) {
      github.createRepo(gitopsRepo, "GitOps state managed by DeveloperHub", true);
      github.putFile(login, gitopsRepo, "README.md",
          "# GitOps state\nArgo CD Applications generated by DeveloperHub. Do not edit by hand.\n", "Initialize");
      for (String e : List.of("dev", "staging"))
        github.putFile(login, gitopsRepo, "apps/" + e + "/.gitkeep", "keep\n", "Init " + e);
    }
    String path = "apps/" + env + "/" + name + ".yaml";
    github.upsertFile(login, gitopsRepo, path, application(name, owner, env, login), "Add " + name + " to " + env);
    return "https://github.com/" + login + "/" + gitopsRepo + "/blob/main/" + path;
  }

  static String application(String name, String owner, String env, String login) {
    return """
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: %1$s-%3$s
          namespace: argocd
          labels:
            app.kubernetes.io/managed-by: developerhub
            developerhub/owner: %2$s
        spec:
          project: default
          source:
            repoURL: https://github.com/%4$s/%1$s
            targetRevision: main
            path: helm
            helm:
              valuesObject:
                image:
                  repository: ghcr.io/%5$s/%1$s
                  tag: latest
                imagePullSecrets:
                  - name: ghcr-pull
          destination:
            server: https://kubernetes.default.svc
            namespace: %2$s-%3$s
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
        """.formatted(name, owner, env, login, login.toLowerCase());
  }
}
