package dev.developerhub;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.time.Instant;
import java.util.*;

@RestController
@RequestMapping("/api")
public class ProvisionController {
  public record ServiceRequest(
      @Pattern(regexp = "^[a-z][a-z0-9-]{2,40}$") String name,
      @Pattern(regexp = "Java") String language,
      @Pattern(regexp = "Spring Boot") String framework,
      @Pattern(regexp = "PostgreSQL|None") String database,
      @Pattern(regexp = "dev|staging|prod") String environment,
      @Pattern(regexp = "^[a-z][a-z0-9-]{1,30}$") String owner, boolean observability, String requestedBy) {}
  public record Result(String id, String status, List<String> steps, String repoUrl, String dashboardUrl) {}
  public record AuditEvent(String actor, String action, String resource, String result, Instant timestamp) {}

  private final List<AuditEvent> audit = Collections.synchronizedList(new ArrayList<>());
  private final TemplateRenderer renderer;
  private final GitHubClient github;
  private final GitOpsWriter gitops;

  public ProvisionController(TemplateRenderer renderer, GitHubClient github, GitOpsWriter gitops) {
    this.renderer = renderer;
    this.github = github;
    this.gitops = gitops;
  }

  @PostMapping("/provision")
  public Result provision(@Valid @RequestBody ServiceRequest r) {
    List<String> steps = new ArrayList<>();
    steps.add("1 validated name, ownership, resources");

    if ("prod".equals(r.environment())) {   // guardrail: nothing is created until approved
      steps.add("approval required before provisioning production");
      audit(r, "PENDING_APPROVAL");
      return new Result(UUID.randomUUID().toString(), "PENDING_APPROVAL", steps, null, null);
    }

    try {
      Map<String, String> files = renderer.render(r.name(), r.owner());
      String repoUrl = github.createRepoAndPush(r.name(), "Generated by DeveloperHub for team " + r.owner(), files);
      steps.add("2 repository created from controlled template: " + files.size() + " files pushed");
      steps.add("3 service metadata + CI workflow committed (part of template push)");
      if ("PostgreSQL".equals(r.database())) steps.add("4 terraform request: NOT IMPLEMENTED YET (phase 6)");
      String gitopsUrl = gitops.write(r.name(), r.owner(), r.environment());
      steps.add("5 gitops values + argo cd application written: " + gitopsUrl);
      steps.add("6 catalog registration: NOT IMPLEMENTED YET (phase 1)");
      steps.add("7 argo cd deploy: Argo CD syncs the gitops repo (up to ~3 min, or press Refresh)");
      steps.add("8 dashboard + runbook links: NOT IMPLEMENTED YET (phase 7)");
      audit(r, "REPO_CREATED");
      return new Result(UUID.randomUUID().toString(), "IN_PROGRESS", steps, repoUrl, null);
    } catch (RuntimeException e) {
      audit(r, "FAILED");
      throw e;
    }
  }

  private void audit(ServiceRequest r, String result) {
    audit.add(new AuditEvent(r.requestedBy(), "provision", r.name(), result, Instant.now()));
  }

  @GetMapping("/audit")
  public List<AuditEvent> audit() { return audit; }

  @ExceptionHandler(GitHubClient.GitHubException.class)
  public ResponseEntity<Map<String, String>> github(GitHubClient.GitHubException e) {
    int status = e.status == 422 ? 409 : (e.status >= 400 && e.status < 600 ? e.status : 502);
    String msg = e.status == 422 ? e.getMessage() + " (repository name probably already exists)" : e.getMessage();
    return ResponseEntity.status(status).body(Map.of("error", msg));
  }

  @ExceptionHandler(IllegalStateException.class)
  public ResponseEntity<Map<String, String>> state(IllegalStateException e) {
    return ResponseEntity.status(500).body(Map.of("error", e.getMessage()));
  }
}
