image:
  repository: ghcr.io/company/${{values.name}}
  tag: latest
replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
imagePullSecrets: []
secretRef:
  name: ${{values.name}}-db
  vaultPath: secret/${{values.name}}
