image:
  repository: ghcr.io/${{values.repoOwner}}/${{values.name}}
  tag: pending
replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
imagePullSecrets: []
ingress:
  enabled: false
  className: nginx
  host: ${{values.name}}-${{values.environment}}.${{values.domain}}
  tlsSecret: ""
database:
  enabled: false
  secretName: ${{values.name}}-db
  externalSecret: true
  host: pending
  port: 5432
  name: service
  storeName: developerhub-aws
  remoteKey: ${{values.name}}/${{values.environment}}/db
observability:
  enabled: ${{values.observability}}
  otlpEndpoint: http://otel-collector.observability:4318/v1/traces


registrySecret:
  enabled: false
  storeName: developerhub-aws
  remoteKey: developerhub/ghcr
