{{- if and .Values.database.enabled .Values.database.externalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.database.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%v/%s?sslmode=require" .Values.database.host .Values.database.port .Values.database.name | quote }}
        SPRING_DATASOURCE_USERNAME: '{{ `{{ .username }}` }}'
        SPRING_DATASOURCE_PASSWORD: '{{ `{{ .password }}` }}'
  dataFrom:
    - extract:
        key: {{ .Values.database.remoteKey | quote }}
{{- end }}

