apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata: {name: create-java-service, title: Create Java Service}
spec:
  owner: platform
  type: service
  parameters:
    - title: Create New Service
      required: [name, owner, environment]
      properties:
        name: {type: string, default: payment-service}
        language: {type: string, enum: [Java], default: Java}
        framework: {type: string, enum: [Spring Boot], default: Spring Boot}
        database: {type: string, enum: [PostgreSQL, None], default: PostgreSQL}
        environment: {type: string, enum: [dev, staging, prod], default: dev}
        owner: {type: string, default: payments, ui:field: OwnerPicker}
        observability: {type: boolean, default: true}
  steps:
    - id: provision
      name: Call Workflow API
      action: http:backstage:request
      input: {method: POST, path: /proxy/platform-api/api/provision, body: "${{ parameters }}"}
  output:
    links:
      - {title: Repository, url: "${{ steps.provision.output.body.repoUrl }}"}
      - {title: Dashboard, url: "${{ steps.provision.output.body.dashboardUrl }}"}
